# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net
# https://github.com/actions

name: CICD

on:
  push:
    paths:
      - '.github/**'
      - 'source/**'
      - 'workflows/**'
    branches:
      - 'master'
      - 'release'
      - 'develop'
      - 'hotfix'
      - 'master/**'
      - 'release/**'
      - 'develop/**'
      - 'hotfix/**'
  repository_dispatch:
    types: 
      - builddispatch
  workflow_dispatch:

jobs:

  builddeploy:
    if: (github.event_name == 'workflow_dispatch') || (github.event_name == 'repository_dispatch') ||  github.event.head_commit.committer.name == 'Github'
 
    runs-on: ubuntu-latest
    
    env:
      GH_TOKEN: ${{ github.token }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup-dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Diagnostic print enviroment vars
      run: printenv

    - name: Display dotnet version
      run: dotnet --version    

    - name: Display powershell core version
      run: pwsh --version

    - name: Workflow Build/Deploy
      run: workflows/cicd.ps1 "${{ secrets.NUGET_PAT }}" "${{ secrets.NUGET_TEST_PAT }}"
      shell: pwsh 

